/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
 * Generated on: 19-Nov-2016 18:30:35
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 64
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s16,16 -> [-5.000000e-01 5.000000e-01)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Specify Precision
 *   Output          : s34,31 -> [-4 4)
 *   Product         : s31,31 -> [-5.000000e-01 5.000000e-01)
 *   Accumulator     : s34,31 -> [-4 4)
 *   Round Mode      : convergent
 *   Overflow Mode   : wrap
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\MATLAB Production Server\R2015a\extern\include\tmwtypes.h 
 */
const int BL = 64;
const int16_T B[64] = {
      241,    192,   -108,   -620,   -965,   -789,   -158,    403,    376,
     -196,   -672,   -453,    325,    836,    426,   -581,  -1082,   -373,
      936,   1382,    233,  -1480,  -1789,     65,   2400,   2430,   -742,
    -4399,  -3925,   3058,  13827,  21904,  21904,  13827,   3058,  -3925,
    -4399,   -742,   2430,   2400,     65,  -1789,  -1480,    233,   1382,
      936,   -373,  -1082,   -581,    426,    836,    325,   -453,   -672,
     -196,    376,    403,   -158,   -789,   -965,   -620,   -108,    192,
      241
};
